# [Air](https://github.com/cosmtrek/air) Configuration file in TOML format

# work dir
# Use . or absolute path, please note that the `tmp_dir` directory must be in the `root` directory
root = "."
tmp_dir = "tmp"

[build]
# Just write the shell commands you normally use to compile. You can also use `make`
# Windows platform example: cmd = "go build -o tmp\main.exe ."
cmd = "task build"
# The name of the binary file obtained by the `cmd` command
# Example for Windows platform: bin = "tmp\main.exe"
bin = "bin/goflat"
args_bin = ["serve", "--dev"]

# Listens to files with the following file extensions.
include_ext = [
  ".air.toml",
  "css",
  "go",
  "gohtml",
  "html",
  "js",
  "templ",
  "tmpl",
]

# Ignore these file extensions or directories
exclude_dir = [".git", "assets", "tmp", "node_modules"]
exclude_regex = [
  "_test.go",
  "_templ\\.go",
  "bin/pb_data",
  "pb_data",
  "bin",
  ".md",
]

# Exclude the following documents
exclude_file = []

# If the file changes too frequently, it is not necessary to trigger a build on every change. You can set the delay time for triggering the build
delay = 1000
# Stop running old binaries when a build error occurs.
stop_on_error = true
# The name of the log file that is placed in your `tmp_dir`
log = "air_errors.log"

[log]
# Show log time
time = true

[color]
# Customize the colors displayed for each section. If the color is not found, use the original application log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
keep_scroll = true
