---
version: '3'
dotenv: [.env]
vars:
  APP_NAME: goflat
  APP_IMAGE_REGISTRY: silveiralexf/goflat:latest
  TAILWIND_CONFIG: '{{.USER_WORKING_DIR}}/tailwind.config.js'
  TAILWIND_SRC: '{{.USER_WORKING_DIR}}/site/static/src/input.css'
  TAILWIND_OUT: '{{.USER_WORKING_DIR}}/site/static/public/out.css'
  TEMPLATES: '{{.USER_WORKING_DIR}}/site/pages/templates/*.gohtml'
  SHELL: /usr/bin/env bash -o pipefail
  GOLANGCI_LINT_VERSION: v1.57.2
includes:
  docs:
    taskfile: ./build/tasks/docs/Taskfile.yml
  docker:
    taskfile: ./build/tasks/docker/Taskfile.yml
  install:
    taskfile: ./build/tasks/install/Taskfile.yml
  go:
    taskfile: ./build/tasks/go/Taskfile.yml
  test:
    taskfile: ./build/tasks/test/Taskfile.yml
tasks:
  default:
    desc: Lists available commands
    cmds:
      - task: hooks
      - task -l
    silent: true
  list:
    desc: Lists available commands
    cmds: [task -l]
  hooks:
    desc: Setup git hooks locally
    cmds: [cp scripts/hooks/* .git/hooks/]
    silent: true
  precommit:
    desc: Verifies and fix requirements for new commits
    cmds: [scripts/hooks/pre-commit]
  run:
    desc: Run the app
    deps: [install:air, go:tidy, go:fmt]
    cmds: [air]
  build:
    desc: Build binary.
    deps: [build:css]
    cmds:
      - rm -rf bin/{{.APP_NAME}}
      - go build -trimpath -o bin/{{.APP_NAME}} .
  build:css:
    desc: Buids CSS assets
    cmds: ['tailwindcss -m -i "{{.TAILWIND_SRC}}" -o "{{.TAILWIND_OUT}}"']
