name: build-and-test

on:
  push:
    paths:
      - .github/workflows/**
      - main.go
      - pkg/**
      - web/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    permissions:
      contents: write
      issues: write
      pull-requests: write

    strategy:
      matrix:
        go-version: ["1.22.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: ${{ github.workspace }}/go.sum

      - name: Setup Go Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Tooling
        run: |
          task install:golangci-lint

      - name: Download dependencies
        run: |
          task go:download

      - name: Fmt, Vet and Lint
        run: |
          task go:fmt
          task go:vet
          task go:lint

      - name: Unit Tests
        run: |
          task test:coverage

      - name: Patch Coverage
        uses: seriousben/go-patch-cover-action@v1
        with:
          version: v0.2.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_filename: ${{ github.workspace }}/build/reports/cover.out

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.go-version }}
          path: ${{ github.workspace }}/build/reports/*
